### ISSUE TITLE
Unclear how to create fragments.tsv file

### ISSUE THREAD

**Issue by TheBorgy** [satijalab/PASTA#6]
I'm currently working on applying PASTA, and I'm having trouble creating a fragments TSV file using Sinto. I've looked through the documentation and searched online, but I'm still not clear on how to do it.

Here's what I've tried so far:

I've installed Sinto and its dependencies using pip.
I've run the blocks function in Sinto to create a BED file of the genomic blocks or fragments from PolyApipe Bam output.
However, I'm not sure how to convert the BED file to a TSV file that I can use in my analysis or if this is even the right file

I would really appreciate any guidance or resources that you could provide to help me create a fragments TSV file and what was used as an input to create it.

Thank you for your time and assistance.

**Comment by ntsopoul** [comment]
I have the same question. TheBorgy, did you manage? Can you share the code you used for blocks function in Sito ?

**Comment by mhkowalski** [comment]
Hi, 

Thanks for your question. We are working on making the documentation more comprehensive and clear. In the meantime, please see below for an example of how to build this file (using a bam file derived from a 10X pbmc experiment). We called it a fragment file due to the similar format with ATAC-seq, but really it is a BED file that is generated from the bam file you get from cellranger (not the polyApipe output). 

```
#!/bin/bash

module load python/3.7.1
module load bedtools
module load samtools


wget https://cf.10xgenomics.com/samples/cell-exp/3.0.0/pbmc_1k_v3/pbmc_1k_v3_possorted_genome_bam.bam

BAM=pbmc_1k_v3_possorted_genome_bam.bam
OUT=pbmc_1k_v3
THREADS=20

#extract reads used in UMI counting
#see https://www.10xgenomics.com/resources/analysis-guides/tutorial-navigating-10x-barcoded-bam-files
samtools view ${BAM} | LC_ALL=C grep "xf:i:25" > body_filtered_sam
samtools view -H ${BAM} > header
cat header body_filtered_sam | samtools view -b > ${OUT}.filtered.bam
samtools index ${OUT}.filtered.bam 

#make BED file with sinto
sinto blocks -b ${OUT}.filtered.bam --blocks ${OUT}.blocks.bed -p ${THREADS}
sort -k1,1 -k2,2n ${OUT}.blocks.bed > ${OUT}.blocks.sort.bed
bgzip -@ ${THREADS} ${OUT}.blocks.sort.bed
tabix -p bed ${OUT}.blocks.sort.bed.gz
```


The resulting file has the format Chromsome, start position, end position, cell barcode, UMI.
```
zcat  pbmc_1k_v3.blocks.sort.bed.gz  | head
1	89313	89374	GCTGCAGGTTGACGGA-1	ATGAATTCGTTT
1	89348	89411	CTGCCTATCTTGATTC-1	CGGGTACTGCGC
1	89398	89489	TCACACCCAGCAGAAC-1	GACAAAAATCCA
1	89412	89503	GCGAGAAAGTTGTAGA-1	TTGTAAAATACG
1	89421	89512	GGTCTGGTCAGACATC-1	GGAAATCTGCGT
1	89968	90050	TGAGCGCCACTATGTG-1	GTTAGGTCGTTT
1	90286	90295	TGAGCGCCACTATGTG-1	GTTAGGTCGTTT
1	91405	91496	GCTGAATCACACGGAA-1	GAACTAGGACGC
1	91443	91534	CAACAACTCGATACTG-1	CCCCAGAAGGCG
1	778933	778997	GTAATCGGTTGCGAAG-1	TAGGAGTAGGGC
```
